/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Divider: typeof import('primevue/divider')['default']
    HospitalStats: typeof import('./src/components/HospitalStats.vue')['default']
    Image: typeof import('primevue/image')['default']
    LineChart: typeof import('./src/components/LineChart.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Panel: typeof import('primevue/panel')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectHospital: typeof import('./src/components/SelectHospital.vue')['default']
    SelectStatsType: typeof import('./src/components/SelectStatsType.vue')['default']
  }
}
